import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
const inter = Inter({ subsets: ["latin"] });
import styles from "@/styles/Layout.module.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <div className={styles.container}>
          <main className={styles.main}>
            <Header />
            <div>{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
